# Generated by Django 4.0.3 on 2022-03-20 02:01

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='About',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('first_name', models.CharField(max_length=100)),
                ('last_name', models.CharField(max_length=100)),
                ('photo', models.ImageField(upload_to='media/profile/')),
                ('address', models.CharField(max_length=100)),
                ('phone_number', models.CharField(max_length=100)),
                ('email', models.EmailField(max_length=100)),
                ('describe_yourself', models.TextField()),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('linkedin', models.URLField()),
                ('github', models.URLField()),
                ('twitter', models.URLField()),
                ('facebook', models.URLField()),
            ],
        ),
    ]
