# Generated by Django 4.0.3 on 2022-03-20 02:50

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('webpages', '0002_experience'),
    ]

    operations = [
        migrations.RenameField(
            model_name='experience',
            old_name='from_date',
            new_name='from_month',
        ),
        migrations.RenameField(
            model_name='experience',
            old_name='to_date',
            new_name='to_month',
        ),
    ]
