# Generated by Django 4.0.3 on 2022-03-20 03:09

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('webpages', '0004_education'),
    ]

    operations = [
        migrations.AddField(
            model_name='education',
            name='college_name',
            field=models.CharField(default=2, max_length=100),
            preserve_default=False,
        ),
    ]
