# Generated by Django 4.0.3 on 2022-03-20 03:12

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('webpages', '0005_education_college_name'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='education',
            name='description',
        ),
    ]
