# Generated by Django 4.0.3 on 2022-03-20 03:29

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('webpages', '0007_awards'),
    ]

    operations = [
        migrations.CreateModel(
            name='Interests',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('interests_name', models.CharField(max_length=100)),
                ('interests_description', models.TextField()),
                ('created_at', models.DateTimeField(auto_now_add=True)),
            ],
        ),
        migrations.CreateModel(
            name='Skill',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('skill_name', models.CharField(max_length=100)),
                ('skill_level', models.CharField(choices=[('Beginner', 'Beginner'), ('Intermediate', 'Intermediate'), ('Expert', 'Expert')], max_length=100)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
            ],
        ),
        migrations.AlterField(
            model_name='education',
            name='branch',
            field=models.CharField(choices=[('Computers Science Engineering(CSE)', 'Computers Science Engineering(CSE)'), ('Electronics and Communication(ECE)', 'Electronics and Communication(ECE)'), ('Electrical and Electronics(EEE)', 'Electrical and Electronics(EEE)'), ('ME', 'ME'), ('CE', 'CE'), ('CIVIL ENGINEERING', 'CIVIL ENGINEERING'), ('MECH ENGINEERING', 'MECH ENGINEERING'), ('PHYSICS', 'PHYSICS'), ('CHEMISTRY', 'CHEMISTRY'), ('MATHEMATICS', 'MATHEMATICS'), ('PHYSICAL', 'PHYSICAL'), ('BIOLOGY', 'BIOLOGY'), ('MUSIC', 'MUSIC'), ('PHILOSOPHY', 'PHILOSOPHY'), ('SOCIAL', 'SOCIAL'), ('COMPUTER', 'COMPUTER'), ('ENGLISH', 'ENGLISH'), ('HISTORY', 'HISTORY'), ('GEOGRAPHY', 'GEOGRAPHY'), ('ARTS', 'ARTS'), ('SCIENCE', 'SCIENCE'), ('OTHERS', 'OTHERS')], max_length=100),
        ),
        migrations.AlterField(
            model_name='education',
            name='degree',
            field=models.CharField(choices=[('B.Sc', 'B.Sc'), ('M.Sc', 'M.Sc'), ('B.A', 'B.A'), ('M.A', 'M.A'), ('B.Com', 'B.Com'), ('M.Com', 'M.Com'), ('B.Tech', 'B.Tech'), ('M.Tech', 'M.Tech'), ('B.Arch', 'B.Arch'), ('M.Arch', 'M.Arch'), ('B.Ams', 'B.Ams'), ('M.Ams', 'M.Ams'), ('B.Pharma', 'B.Pharma'), ('M.Pharma', 'M.Pharma'), ('B.Sc.Engg', 'B.Sc.Engg'), ('M.Sc.Engg', 'M.Sc.Engg'), ('B.Sc.Engg', 'B.Sc.Engg')], max_length=100),
        ),
    ]
