# Generated by Django 4.0.3 on 2022-03-20 05:12

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('webpages', '0009_workflow_alter_skill_skill_name'),
    ]

    operations = [
        migrations.CreateModel(
            name='Settings',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('theme_color', models.CharField(default='#BD5D38', max_length=100)),
                ('theme_color_dark', models.CharField(default='#BD5D38', max_length=100)),
            ],
        ),
    ]
