# Generated by Django 4.0.3 on 2022-03-20 05:21

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('webpages', '0010_settings'),
    ]

    operations = [
        migrations.DeleteModel(
            name='Settings',
        ),
    ]
